apiVersion: v1
kind: Service
metadata:
  name: berkeley-cds-service
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: berkeley-cds-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer